Bname: threeML
channels:
  - conda-forge
  - threeml
dependencies:
  - python=3.9  
  - numpy=1.23.5
  - matplotlib=3.7.1
  - scipy=1.10.1
  - astropy=6.0.0
  - h5py=3.8.0
  - numba=0.56.4
  - astromodels=*=*threeml
  - threeml
