#!/bin/bash

# Update conda first
conda update -n base -c conda-forge conda -y

# Initialize conda
eval "$(conda shell.bash hook)"
conda init bash
source ~/.bashrc

# Create environment
conda create --name threeML -c conda-forge python=3.9 numpy scipy matplotlib -y

# Initialize and activate
source activate threeML

# Install threeML packages
conda install -c conda-forge -c threeml astromodels threeml -y
